services:
  mongodb:
    image: mongo:7
    container_name: document-batch-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: document_batch_service
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7
    container_name: document-batch-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: