import PDFDocument from "pdfkit";

export interface GenerateDocumentPdfInput {
  batchId: string;
  documentId: string;
  userId: string;
}

export async function generateDocumentPdfBuffer(
  input: GenerateDocumentPdfInput
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const pdf = new PDFDocument({
      margin: 50,
      size: "A4"
    });

    const chunks: Buffer[] = [];

    pdf.on("data", (chunk: Buffer) => {
      chunks.push(chunk);
    });

    pdf.on("end", () => {
      resolve(Buffer.concat(chunks));
    });

    pdf.on("error", (error) => {
      reject(error);
    });

    pdf.fontSize(20).text("Generated Document", {
      align: "center"
    });

    pdf.moveDown();
    pdf.fontSize(12).text(`Batch ID: ${input.batchId}`);
    pdf.text(`Document ID: ${input.documentId}`);
    pdf.text(`User ID: ${input.userId}`);
    pdf.text(`Generated at: ${new Date().toISOString()}`);

    pdf.moveDown();
    pdf.text("This is a test PDF generated by the worker.");

    pdf.end();
  });
}